server:
  port: 80
spring:
  application:
    name: cloud-order-service

eureka:
  client:
    register-with-eureka: true    # 表示自己会注册进 eureka 注册服务中心
    fetch-registry: true    # 是否从 eureka 抓取已有的注册信息， 默认为 true 单节点无所谓，多节点必须设置为 true才能配合 Ribbon 进行负载均衡
    service-url:
#      defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
